# 定义 test 和 package 两个 Stages
stages:
  - build
  - test
  - package
  - deploy



# 定义 package 阶段的一个 job
package-job:
  stage: package
  script:
    - echo "Hello, package-job"
    - echo "I am in package stage"

# 定义 test 阶段的一个 job
test-job:
  stage: test
  script:
    - echo "TODO test"

# 定义 build 阶段的一个 job
build-job:
  stage: build
  script:
    - echo "执行gitbook build 打包命令"
    - gitbook build
    - echo "打包完成"


# 定义 deploy 阶段的一个 job
deploy-job:
  stage: deploy
  script:
    - echo "部署服务开始"
    - rm -rf /home/ftpuser/gitbook/java
    - cp -r _book /home/ftpuser/gitbook/java
    - echo "部署完成"